### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [Jmclerck/webicons.zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

**Comment by Jmclerck** [comment]
Hi @unixorn, I've added a screenshot as you request with commit 0c931b9d. Feel free to open a new issue if there us anything else you need and thanks for your interest!

**Comment by unixorn** [comment]
Thanks! Added as of [awesome-zsh-plugins/commit/3d57e1fd9eb97ed434f6533bbe651aa7c86874ad](https://github.com/unixorn/awesome-zsh-plugins/commit/3d57e1fd9eb97ed434f6533bbe651aa7c86874ad)

Let me know if you want the description changed or just file a PR 😄
